/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Calculate calc = new Calculate();

    System.out.println(new App().getGreeting());
    System.out.println(calc.sum_and(2, 3));
    System.out.println(calc.sum_to(1, 10));
    System.out.println(calc.odd_even(1, 10));
  }
}
